version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql
#  config-server:
#    image: config-server:0.0.1-SNAPSHOT
#    ports:
#      - "8888:8888"
#    environment:
#      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
#    networks:
#      backend:
#        aliases:
#          - "config-server"
volumes:
  mysql-db:
networks:
  backend:
    driver: bridge
