spring:
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin
server:
  port: 8070
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # don't register with the Eureka service
    fetchRegistry: false # don't cache registry information locally
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0 # speed up for dev
      
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
   
