server:
  port: 8081
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
rates:
  out-of-service: false # Out of service imitate for CircuitBreaker testing
keycloak:
  realm: store-realm # Keycloak realm name
  auth-server-url: http://keycloak:8080/auth
  ssl-required: external
  resource: store # Keycloak client id
  credentials:
    secret: ZZG9y0QdIcw75zQuyvzRcmOkkN0KqoJ9 # Study purpose
  use-resource-role-mappings: true
  bearer-only: true
spring:
  cloud:
    stream:
      bindings:
        output-out-0:
          destination: rates
