server:
  port: 8082
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
  cloud:
    stream:
      bindings:
        input-in-0:
          destination: "rates"
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
keycloak:
  realm: store-realm # Keycloak realm name
  auth-server-url: http://keycloak:8080/auth
  ssl-required: external
  resource: store # Keycloak client id
  credentials:
    secret: vrInKPb0ZFZ2JPI3Jk40A6yIxKcfFu2F # Study purpose
  use-resource-role-mappings: true
  bearer-only: true
redis:
  server: redis
  port: 6379
logging:
  level:
    ru.mironovmike: debug