server:
  port: 8082
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
keycloak:
  realm: store-realm # Keycloak realm name
  auth-server-url: http://keycloak:8080/auth
  ssl-required: external
  resource: store # Keycloak client id
  credentials:
    secret: eUje5U671G3v1fKduCc8pVGUH05iQMuY # Study purpose
  use-resource-role-mappings: true
  bearer-only: true